// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "quoteable-20181124161016--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://quoteable-20181124161016--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:15b2d2c3-f3f1-4ee6-9870-e282bdd66489",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KI3auPQwX",
    "aws_user_pools_web_client_id": "5ecmconttn6f69g4ib02um3r6k",
    "aws_cloud_logic_custom": [
        {
            "name": "quotes",
            "endpoint": "https://qt8byfjwh5.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
